import { Router, type IRouter } from "express";
import { eq, and, ne, inArray } from "drizzle-orm";
import { z } from "zod/v4";
import { db, driversTable, usersTable, geoZonesTable, driverServiceZonesTable } from "@workspace/db";
import { requireAdmin } from "../middleware/auth.js";
import { tableExists } from "../lib/schemaGuards.js";

/**
 * Full administrative edit of a chauffeur record.
 *
 * PATCH /drivers/:id reached twelve of the roughly thirty columns on the table:
 * an admin could change the vehicle make but not its plate, the rating but not
 * the licence expiry, and nothing at all about insurance, registration or which
 * areas the driver works. As with the booking equivalent, that endpoint's body
 * is generated by orval from lib/api-spec/openapi.yaml, so this is a separate
 * route with a hand-written schema and the generated contract is untouched.
 *
 * Banking details are deliberately NOT here. They live behind
 * PATCH /drivers/:id/payout and PATCH /admin/drivers/:id/bank, which encrypt
 * before writing and never read the values back; routing them through a
 * general-purpose edit form would mean either duplicating that handling or
 * losing it.
 */

const router: IRouter = Router();

/** Trim to null, so clearing a field in the form actually clears the column. */
const optionalText = (max: number) =>
  z.string().trim().max(max).nullable().optional().transform(v => (v == null || v === "" ? null : v));

const EditDriverBody = z.object({
  // Identity
  name: z.string().trim().min(1).max(200).optional(),
  email: z.string().trim().email().max(320).optional(),
  phone: z.string().trim().min(3).max(40).optional(),
  licenseNumber: optionalText(60),
  licenseExpiry: optionalText(20),

  // Vehicle
  vehicleYear: optionalText(8),
  vehicleMake: optionalText(60),
  vehicleModel: optionalText(60),
  vehicleColor: optionalText(40),
  vehicleClass: optionalText(50),
  passengerCapacity: z.number().int().min(0).max(60).nullable().optional(),
  luggageCapacity: z.number().int().min(0).max(60).nullable().optional(),
  hasCarSeat: z.boolean().optional(),

  // Registration & insurance
  regVin: optionalText(40),
  regPlate: optionalText(20),
  regExpiry: optionalText(20),
  insuranceExpiry: optionalText(20),

  // Standing
  status: z.enum(["pending", "available", "busy", "offline", "paused"]).optional(),
  approvalStatus: z.enum(["pending", "approved", "rejected"]).optional(),
  rejectionReason: optionalText(500),
  complianceHold: z.boolean().optional(),
  isOnline: z.boolean().optional(),
  rating: z.number().min(0).max(5).nullable().optional(),

  // Service areas. The legacy free-text label is kept editable so existing
  // records stay readable, but zone ids are what the trip pool actually uses.
  serviceArea: optionalText(200),
  serviceZoneIds: z.array(z.number().int().positive()).max(50).optional(),
}).strict();

router.patch("/admin/drivers/:id/details", requireAdmin, async (req, res): Promise<void> => {
  const id = parseInt(String(req.params["id"] ?? ""), 10);
  if (!Number.isFinite(id) || id <= 0) {
    res.status(400).json({ error: "Invalid driver id" });
    return;
  }

  const parsed = EditDriverBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: z.prettifyError(parsed.error) });
    return;
  }
  const body = parsed.data;

  const [before] = await db.select().from(driversTable).where(eq(driversTable.id, id));
  if (!before) {
    res.status(404).json({ error: "Driver not found" });
    return;
  }

  // ── Email is the driver's login, and unique on two tables ──────────────────
  // drivers.email has a unique constraint, and the linked users row is what the
  // driver actually signs in with. Changing one without the other silently
  // splits the account: the admin sees the new address, the driver still logs
  // in with the old one, and payout emails go somewhere nobody reads. Both are
  // checked for collisions first so the failure is a 409 rather than a raw
  // constraint violation surfacing as a 500.
  const nextEmail = body.email?.toLowerCase();
  const emailChanged = nextEmail != null && nextEmail !== before.email.toLowerCase();
  if (emailChanged) {
    const [clashingDriver] = await db
      .select({ id: driversTable.id })
      .from(driversTable)
      .where(and(eq(driversTable.email, nextEmail), ne(driversTable.id, id)));
    if (clashingDriver) {
      res.status(409).json({ error: "Another driver already uses that email address." });
      return;
    }

    const clashingUsers = await db
      .select({ id: usersTable.id })
      .from(usersTable)
      .where(eq(usersTable.email, nextEmail));
    const clashingOtherUser = clashingUsers.find(u => u.id !== before.userId);
    if (clashingOtherUser) {
      res.status(409).json({ error: "Another account already uses that email address." });
      return;
    }
  }

  const updates: Partial<typeof driversTable.$inferInsert> = {};
  const assign = <K extends keyof typeof body>(key: K, column: keyof typeof updates) => {
    if (body[key] !== undefined) (updates as Record<string, unknown>)[column as string] = body[key];
  };

  if (body.name !== undefined) updates.name = body.name;
  if (nextEmail !== undefined) updates.email = nextEmail;
  if (body.phone !== undefined) updates.phone = body.phone;
  assign("licenseNumber", "licenseNumber");
  assign("licenseExpiry", "licenseExpiry");
  assign("vehicleYear", "vehicleYear");
  assign("vehicleMake", "vehicleMake");
  assign("vehicleModel", "vehicleModel");
  assign("vehicleColor", "vehicleColor");
  assign("vehicleClass", "vehicleClass");
  assign("passengerCapacity", "passengerCapacity");
  assign("luggageCapacity", "luggageCapacity");
  assign("hasCarSeat", "hasCarSeat");
  assign("regVin", "regVin");
  assign("regPlate", "regPlate");
  assign("regExpiry", "regExpiry");
  assign("insuranceExpiry", "insuranceExpiry");
  assign("status", "status");
  assign("approvalStatus", "approvalStatus");
  assign("rejectionReason", "rejectionReason");
  assign("complianceHold", "complianceHold");
  assign("isOnline", "isOnline");
  assign("serviceArea", "serviceArea");
  // rating is numeric on the table, so it is stored as a string like the rest.
  if (body.rating !== undefined) updates.rating = body.rating == null ? null : String(body.rating);

  // A driver taken off approved must not keep working the rest of the shift on
  // a stale session's cached status.
  if (body.approvalStatus === "rejected" || body.status === "paused") {
    updates.isOnline = false;
  }

  const hasFieldUpdates = Object.keys(updates).length > 0;
  if (!hasFieldUpdates && body.serviceZoneIds === undefined) {
    res.status(400).json({ error: "No fields to update" });
    return;
  }

  // ── Service zone assignment ───────────────────────────────────────────────
  // Validated before anything is written: an unknown or non-service zone id
  // should be rejected outright rather than half-applied alongside the field
  // edits.
  let zoneIds: number[] | null = null;
  if (body.serviceZoneIds !== undefined) {
    if (!(await tableExists("public.driver_service_zones"))) {
      res.status(503).json({
        error: "Service areas are not available yet — migration 0009_service_areas.sql has not been applied to this database.",
      });
      return;
    }
    zoneIds = [...new Set(body.serviceZoneIds)];
    if (zoneIds.length > 0) {
      const found = await db
        .select({ id: geoZonesTable.id })
        .from(geoZonesTable)
        .where(and(inArray(geoZonesTable.id, zoneIds), eq(geoZonesTable.isServiceArea, true)));
      const foundIds = new Set(found.map(z => z.id));
      const unknown = zoneIds.filter(z => !foundIds.has(z));
      if (unknown.length > 0) {
        res.status(400).json({
          error: `Not a service area: zone ${unknown.join(", ")}. Mark the zone as a service area before assigning drivers to it.`,
        });
        return;
      }
    }
  }

  // Field edits, the users-table email mirror and the zone assignment are one
  // transaction: a driver whose drivers.email moved but whose users.email did
  // not can no longer sign in, and that must not be a state the database can
  // be left in by a mid-write failure.
  const updated = await db.transaction(async tx => {
    let row = before;
    if (hasFieldUpdates) {
      const [r] = await tx.update(driversTable).set(updates).where(eq(driversTable.id, id)).returning();
      if (r) row = r;
    }

    if (emailChanged && before.userId != null) {
      await tx.update(usersTable).set({ email: nextEmail! }).where(eq(usersTable.id, before.userId));
    }

    if (zoneIds != null) {
      // Replace rather than diff: the form always sends the complete set, and a
      // delete-then-insert inside the transaction cannot leave a partial one.
      await tx.delete(driverServiceZonesTable).where(eq(driverServiceZonesTable.driverId, id));
      if (zoneIds.length > 0) {
        await tx.insert(driverServiceZonesTable).values(zoneIds.map(zoneId => ({ driverId: id, zoneId })));
      }
    }

    return row;
  });

  req.log.info(
    { driverId: id, adminUserId: req.currentUser?.userId, fields: Object.keys(updates), emailChanged, zonesSet: zoneIds?.length ?? null },
    "admin_driver_edited",
  );

  const { payoutSsn: _s, payoutRoutingNumber: _r, payoutAccountNumber: _a, ...safe } = updated;
  res.json({
    ok: true,
    driver: {
      ...safe,
      rating: updated.rating != null ? parseFloat(updated.rating) : null,
      createdAt: updated.createdAt.toISOString(),
      updatedAt: updated.updatedAt.toISOString(),
      locationUpdatedAt: updated.locationUpdatedAt ? updated.locationUpdatedAt.toISOString() : null,
    },
    serviceZoneIds: zoneIds,
  });
});

/**
 * GET /admin/drivers/:id/service-zones — which areas this driver works.
 *
 * Returned separately from the driver record because the assignment lives in
 * its own table and the edit form needs it to pre-tick the checkboxes.
 */
router.get("/admin/drivers/:id/service-zones", requireAdmin, async (req, res): Promise<void> => {
  const id = parseInt(String(req.params["id"] ?? ""), 10);
  if (!Number.isFinite(id) || id <= 0) {
    res.status(400).json({ error: "Invalid driver id" });
    return;
  }
  // Answering "none yet" is correct before the migration runs, and keeps the
  // driver edit screen usable instead of erroring on load.
  if (!(await tableExists("public.driver_service_zones"))) {
    res.json({ zoneIds: [], available: false });
    return;
  }
  const rows = await db
    .select({ zoneId: driverServiceZonesTable.zoneId })
    .from(driverServiceZonesTable)
    .where(eq(driverServiceZonesTable.driverId, id));
  res.json({ zoneIds: rows.map(r => r.zoneId), available: true });
});

export default router;
