-- Sensitive-action hardening: short-lived password step-up and durable audit.
ALTER TABLE public.sessions
  ADD COLUMN IF NOT EXISTS step_up_until timestamptz;

CREATE TABLE IF NOT EXISTS public.security_action_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id integer,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS security_action_audit_resource_idx
  ON public.security_action_audit(resource_type, resource_id, created_at DESC);
CREATE INDEX IF NOT EXISTS security_action_audit_actor_idx
  ON public.security_action_audit(actor_user_id, created_at DESC);
ALTER TABLE public.security_action_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.security_action_audit FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS reviews_booking_user_idx
  ON public.reviews(booking_id, user_id);
