-- Schema-only baseline inspected from production on 2026-09-07.
-- Additive reconciliation; never copies customer rows or seeds identities.
-- Supabase CLI unavailable in this environment; reviewed and applied through MCP.
SET search_path=public;
CREATE TABLE IF NOT EXISTS public."booking_driver_blocks" ();
ALTER TABLE public."booking_driver_blocks" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."booking_driver_blocks" ADD COLUMN IF NOT EXISTS "booking_id" integer NOT NULL;
ALTER TABLE public."booking_driver_blocks" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."booking_driver_blocks" ADD COLUMN IF NOT EXISTS "reason" text DEFAULT 'no_confirmation'::text NOT NULL;
ALTER TABLE public."booking_driver_blocks" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."booking_driver_blocks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."booking_driver_blocks" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."booking_extras" ();
ALTER TABLE public."booking_extras" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."booking_extras" ADD COLUMN IF NOT EXISTS "booking_id" integer NOT NULL;
ALTER TABLE public."booking_extras" ADD COLUMN IF NOT EXISTS "extra_service_id" integer NOT NULL;
ALTER TABLE public."booking_extras" ADD COLUMN IF NOT EXISTS "quantity" integer DEFAULT 1 NOT NULL;
ALTER TABLE public."booking_extras" ADD COLUMN IF NOT EXISTS "price_at_booking" numeric(10,2) NOT NULL;
ALTER TABLE public."booking_extras" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."booking_extras" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."booking_itinerary_stops" ();
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "booking_id" integer NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "sequence" integer NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "kind" text NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "address" text NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "lat" numeric(10,7);
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "lng" numeric(10,7);
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "arrived_at" timestamp with time zone;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "departed_at" timestamp with time zone;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "arrived_by_driver_id" integer;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "departed_by_driver_id" integer;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."booking_itinerary_stops" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."booking_itinerary_stops" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."bookings" ();
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "passenger_name" text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "passenger_email" text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "passenger_phone" text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "pickup_address" text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "dropoff_address" text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "pickup_at" timestamp with time zone NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "vehicle_class" text DEFAULT 'standard'::text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "passengers" integer DEFAULT 1 NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "luggage_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "flight_number" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "special_requests" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "price_quoted" numeric(10,2) NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "promo_code" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "discount_amount" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "driver_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "vehicle_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "payment_type" text DEFAULT 'standard'::text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "stripe_payment_intent_id" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "reminder_sent_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "tip_amount" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "tip_payment_intent_id" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "estimated_duration_minutes" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "estimated_distance_miles" numeric(6,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "authorized_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "checklist_completed_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "preferred_driver_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "waypoints" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "charter_mode" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "charter_hours" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "booked_by_user_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "review_request_sent_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "max_miles_per_hour" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "hourly_rate" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "extra_mile_rate" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "trip_started_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "trip_ended_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "extra_charge" numeric(10,2) DEFAULT 0 NOT NULL;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "total_price" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "overage_notified_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "fare_subtotal" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "invoiced_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "selected_vehicle_id" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "tracking_token" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "reminder_24h_sent_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "reminder_2h_sent_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "driver_released_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "cancellation_reason" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "cancellation_notes" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "cancelled_by" text;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "cancelled_at" timestamp with time zone;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "refund_amount" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "pickup_lat" numeric(10,7);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "pickup_lng" numeric(10,7);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "overage_minutes" integer;
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "tax_amount" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "card_fee" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "airport_fee" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "extras_total" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "overage_fare" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "overage_tax" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "overage_card_fee" numeric(10,2);
ALTER TABLE public."bookings" ADD COLUMN IF NOT EXISTS "extra_charge_payment_intent_id" text;
ALTER TABLE public."bookings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."bookings" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."compliance_documents" ();
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "doc_type" text NOT NULL;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending_review'::text NOT NULL;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "file_url" text NOT NULL;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "new_expiry" text;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "admin_notes" text;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "reviewed_at" timestamp with time zone;
ALTER TABLE public."compliance_documents" ADD COLUMN IF NOT EXISTS "submitted_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."compliance_documents" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."compliance_documents" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."corporate_accounts" ();
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "company_name" text NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "billing_email" text NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "billing_address" text;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "net_terms_days" integer DEFAULT 30 NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "volume_discount_pct" numeric(5,2) DEFAULT '0'::numeric NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "credit_limit" numeric(10,2);
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active'::text NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."corporate_accounts" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."corporate_accounts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."corporate_accounts" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."driver_locations" ();
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "id" uuid DEFAULT gen_random_uuid() NOT NULL;
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "booking_id" integer;
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "latitude" double precision NOT NULL;
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "longitude" double precision NOT NULL;
ALTER TABLE public."driver_locations" ADD COLUMN IF NOT EXISTS "recorded_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."driver_locations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."driver_locations" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."driver_service_zones" ();
ALTER TABLE public."driver_service_zones" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."driver_service_zones" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."driver_service_zones" ADD COLUMN IF NOT EXISTS "zone_id" integer NOT NULL;
ALTER TABLE public."driver_service_zones" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."driver_service_zones" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."driver_service_zones" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."driver_vehicles" ();
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "year" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "make" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "model" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "color" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "vehicle_class" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "passenger_capacity" integer;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "luggage_capacity" integer;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "has_car_seat" boolean DEFAULT false NOT NULL;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "reg_plate" text;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "is_default" boolean DEFAULT false NOT NULL;
ALTER TABLE public."driver_vehicles" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."driver_vehicles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."driver_vehicles" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."driver_warnings" ();
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "booking_id" integer;
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "reason" text NOT NULL;
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE public."driver_warnings" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."driver_warnings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."driver_warnings" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."drivers" ();
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "email" text NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "phone" text NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "license_number" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "is_online" boolean DEFAULT false NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "rating" numeric(3,2);
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "total_rides" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "vehicle_year" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "vehicle_make" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "vehicle_model" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "vehicle_color" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "vehicle_class" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "passenger_capacity" integer;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "luggage_capacity" integer;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "has_car_seat" boolean DEFAULT false;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "service_area" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "license_expiry" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "license_doc" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "reg_vin" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "reg_plate" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "reg_expiry" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "reg_doc" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "insurance_expiry" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "insurance_doc" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "approval_status" text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "rejection_reason" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "latitude" numeric(10,7);
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "longitude" numeric(10,7);
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "location_updated_at" timestamp with time zone;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "profile_picture" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_legal_name" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_email" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_ssn" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_bank_name" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_routing_number" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "payout_account_number" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "compliance_hold" boolean DEFAULT false NOT NULL;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "push_token" text;
ALTER TABLE public."drivers" ADD COLUMN IF NOT EXISTS "push_platform" text;
ALTER TABLE public."drivers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."drivers" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."email_logs" ();
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "to" text NOT NULL;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "subject" text NOT NULL;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "type" text NOT NULL;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'skipped'::text NOT NULL;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "error" text;
ALTER TABLE public."email_logs" ADD COLUMN IF NOT EXISTS "sent_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."email_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."email_logs" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."extra_services" ();
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "category" text DEFAULT 'amenity'::text NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "price" numeric(10,2) NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."extra_services" ADD COLUMN IF NOT EXISTS "paid_to_driver" boolean DEFAULT false NOT NULL;
ALTER TABLE public."extra_services" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."extra_services" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."fixed_routes" ();
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "origin_name" text NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "origin_address" text NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "destination_code" text NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "destination_name" text NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "vehicle_class" text DEFAULT 'business'::text NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "fixed_price" numeric(10,2) NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."fixed_routes" ADD COLUMN IF NOT EXISTS "airports_json" jsonb;
ALTER TABLE public."fixed_routes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fixed_routes" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."geo_zones" ();
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "type" text DEFAULT 'circle'::text NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "geometry" text NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "rate_multiplier" real DEFAULT 1.0 NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."geo_zones" ADD COLUMN IF NOT EXISTS "is_service_area" boolean DEFAULT false NOT NULL;
ALTER TABLE public."geo_zones" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."geo_zones" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."legal_acceptances" ();
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "document_type" text NOT NULL;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "document_version" text NOT NULL;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "driver_id" integer;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "booking_id" integer;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "email" text;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "accepted_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "ip_address" text;
ALTER TABLE public."legal_acceptances" ADD COLUMN IF NOT EXISTS "user_agent" text;
ALTER TABLE public."legal_acceptances" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."legal_acceptances" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."managed_travelers" ();
ALTER TABLE public."managed_travelers" ADD COLUMN IF NOT EXISTS "ea_user_id" integer NOT NULL;
ALTER TABLE public."managed_travelers" ADD COLUMN IF NOT EXISTS "traveler_id" integer NOT NULL;
ALTER TABLE public."managed_travelers" ADD COLUMN IF NOT EXISTS "traveler_name" text;
ALTER TABLE public."managed_travelers" ADD COLUMN IF NOT EXISTS "traveler_email" text;
ALTER TABLE public."managed_travelers" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."managed_travelers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."managed_travelers" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."message_events" ();
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "event_type" text NOT NULL;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "message_id" text;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "channel" text;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "to_phone" text;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "from_phone" text;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "message_status" text;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "raw_payload" jsonb NOT NULL;
ALTER TABLE public."message_events" ADD COLUMN IF NOT EXISTS "received_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."message_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."message_events" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."notifications" ();
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "title" text NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "message" text NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "type" text DEFAULT 'system'::text NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "is_read" boolean DEFAULT false NOT NULL;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "booking_id" integer;
ALTER TABLE public."notifications" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."notifications" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."notifications" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."object_owners" ();
ALTER TABLE public."object_owners" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."object_owners" ADD COLUMN IF NOT EXISTS "object_path" text NOT NULL;
ALTER TABLE public."object_owners" ADD COLUMN IF NOT EXISTS "owner_user_id" integer NOT NULL;
ALTER TABLE public."object_owners" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."object_owners" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."object_owners" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."otp_codes" ();
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "phone" text NOT NULL;
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone NOT NULL;
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "otp_hash" text NOT NULL;
ALTER TABLE public."otp_codes" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."otp_codes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."otp_codes" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."password_reset_tokens" ();
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "token" text NOT NULL;
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone NOT NULL;
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "used_at" timestamp with time zone;
ALTER TABLE public."password_reset_tokens" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."password_reset_tokens" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."password_reset_tokens" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."pricing_rules" ();
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "vehicle_class" text;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "base_fare" numeric(10,2) NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "rate_per_mile" numeric(10,2) NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "airport_surcharge" numeric(10,2) DEFAULT '15'::numeric NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "included_miles" numeric(10,1) DEFAULT 0 NOT NULL;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "hourly_rate" numeric(10,2);
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "category" text;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "passengers" integer;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "bags" integer;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."pricing_rules" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."pricing_rules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."pricing_rules" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."promo_codes" ();
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "code" text NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "description" text NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "discount_type" text DEFAULT 'percentage'::text NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "discount_value" numeric(10,2) NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "min_booking_amount" numeric(10,2);
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "max_uses" integer;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "used_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."promo_codes" ADD COLUMN IF NOT EXISTS "max_uses_per_user" integer;
ALTER TABLE public."promo_codes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."promo_codes" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."reviews" ();
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "booking_id" integer NOT NULL;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "rating" integer NOT NULL;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "comment" text;
ALTER TABLE public."reviews" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."reviews" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."reviews" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."saved_addresses" ();
ALTER TABLE public."saved_addresses" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."saved_addresses" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
ALTER TABLE public."saved_addresses" ADD COLUMN IF NOT EXISTS "label" text NOT NULL;
ALTER TABLE public."saved_addresses" ADD COLUMN IF NOT EXISTS "address" text NOT NULL;
ALTER TABLE public."saved_addresses" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."saved_addresses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."saved_addresses" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."sessions" ();
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "token" text NOT NULL;
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "role" text NOT NULL;
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."sessions" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;
ALTER TABLE public."sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."sessions" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."settings" ();
ALTER TABLE public."settings" ADD COLUMN IF NOT EXISTS "key" text NOT NULL;
ALTER TABLE public."settings" ADD COLUMN IF NOT EXISTS "value" text NOT NULL;
ALTER TABLE public."settings" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."settings" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."support_tickets" ();
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "booking_id" integer;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "email" text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "subject" text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "message" text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'open'::text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "priority" text DEFAULT 'medium'::text NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."support_tickets" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."support_tickets" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."support_tickets" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."ticket_messages" ();
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "ticket_id" integer NOT NULL;
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "author_role" text DEFAULT 'passenger'::text NOT NULL;
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "message" text NOT NULL;
ALTER TABLE public."ticket_messages" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."ticket_messages" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ticket_messages" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."user_favorite_drivers" ();
ALTER TABLE public."user_favorite_drivers" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
ALTER TABLE public."user_favorite_drivers" ADD COLUMN IF NOT EXISTS "driver_id" integer NOT NULL;
ALTER TABLE public."user_favorite_drivers" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."user_favorite_drivers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."user_favorite_drivers" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."users" ();
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "name" text NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "email" text NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "phone" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "role" text DEFAULT 'passenger'::text NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "password_hash" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "stripe_customer_id" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "default_payment_method_id" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "cabin_temp_f" integer;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "music_preference" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "quiet_ride" boolean DEFAULT false;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "preferred_beverage" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "opens_own_door" boolean DEFAULT false;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "address_title" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "vip_notes" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "referral_code" text;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "referred_by_user_id" integer;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "referral_rewarded_at" timestamp with time zone;
ALTER TABLE public."users" ADD COLUMN IF NOT EXISTS "corporate_account_id" integer;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."users" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."vehicle_catalog" ();
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "make" text NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "model" text NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "min_year" integer NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "vehicle_types" text NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."vehicle_catalog" ADD COLUMN IF NOT EXISTS "pending_review" boolean DEFAULT false NOT NULL;
ALTER TABLE public."vehicle_catalog" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."vehicle_catalog" FROM anon,authenticated;
CREATE TABLE IF NOT EXISTS public."vehicles" ();
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "id" serial NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "driver_id" integer;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "make" text NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "model" text NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "year" integer NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "color" text NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "plate" text NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "vehicle_class" text DEFAULT 'standard'::text NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "capacity" integer DEFAULT 3 NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "is_available" boolean DEFAULT true NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."vehicles" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."vehicles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."vehicles" FROM anon,authenticated;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_driver_blocks'::regclass AND (conname='booking_driver_blocks_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."booking_driver_blocks" ADD CONSTRAINT "booking_driver_blocks_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_extras'::regclass AND (conname='booking_extras_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."booking_extras" ADD CONSTRAINT "booking_extras_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.bookings'::regclass AND (conname='bookings_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."bookings" ADD CONSTRAINT "bookings_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.compliance_documents'::regclass AND (conname='compliance_documents_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."compliance_documents" ADD CONSTRAINT "compliance_documents_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.corporate_accounts'::regclass AND (conname='corporate_accounts_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."corporate_accounts" ADD CONSTRAINT "corporate_accounts_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_locations'::regclass AND (conname='driver_locations_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."driver_locations" ADD CONSTRAINT "driver_locations_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_service_zones'::regclass AND (conname='driver_service_zones_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."driver_service_zones" ADD CONSTRAINT "driver_service_zones_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_vehicles'::regclass AND (conname='driver_vehicles_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."driver_vehicles" ADD CONSTRAINT "driver_vehicles_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_warnings'::regclass AND (conname='driver_warnings_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."driver_warnings" ADD CONSTRAINT "driver_warnings_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.drivers'::regclass AND (conname='drivers_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."drivers" ADD CONSTRAINT "drivers_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.email_logs'::regclass AND (conname='email_logs_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."email_logs" ADD CONSTRAINT "email_logs_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.extra_services'::regclass AND (conname='extra_services_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."extra_services" ADD CONSTRAINT "extra_services_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.fixed_routes'::regclass AND (conname='fixed_routes_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."fixed_routes" ADD CONSTRAINT "fixed_routes_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.geo_zones'::regclass AND (conname='geo_zones_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."geo_zones" ADD CONSTRAINT "geo_zones_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.legal_acceptances'::regclass AND (conname='legal_acceptances_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."legal_acceptances" ADD CONSTRAINT "legal_acceptances_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.managed_travelers'::regclass AND (conname='managed_travelers_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (ea_user_id, traveler_id)'))) THEN ALTER TABLE public."managed_travelers" ADD CONSTRAINT "managed_travelers_pkey" PRIMARY KEY (ea_user_id, traveler_id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.message_events'::regclass AND (conname='message_events_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."message_events" ADD CONSTRAINT "message_events_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.notifications'::regclass AND (conname='notifications_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.object_owners'::regclass AND (conname='object_owners_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."object_owners" ADD CONSTRAINT "object_owners_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.otp_codes'::regclass AND (conname='otp_codes_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."otp_codes" ADD CONSTRAINT "otp_codes_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.password_reset_tokens'::regclass AND (conname='password_reset_tokens_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.pricing_rules'::regclass AND (conname='pricing_rules_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."pricing_rules" ADD CONSTRAINT "pricing_rules_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.promo_codes'::regclass AND (conname='promo_codes_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."promo_codes" ADD CONSTRAINT "promo_codes_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.reviews'::regclass AND (conname='reviews_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.saved_addresses'::regclass AND (conname='saved_addresses_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."saved_addresses" ADD CONSTRAINT "saved_addresses_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.sessions'::regclass AND (conname='sessions_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.settings'::regclass AND (conname='settings_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (key)'))) THEN ALTER TABLE public."settings" ADD CONSTRAINT "settings_pkey" PRIMARY KEY (key); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.support_tickets'::regclass AND (conname='support_tickets_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."support_tickets" ADD CONSTRAINT "support_tickets_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.ticket_messages'::regclass AND (conname='ticket_messages_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."ticket_messages" ADD CONSTRAINT "ticket_messages_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.user_favorite_drivers'::regclass AND (conname='user_favorite_drivers_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (user_id, driver_id)'))) THEN ALTER TABLE public."user_favorite_drivers" ADD CONSTRAINT "user_favorite_drivers_pkey" PRIMARY KEY (user_id, driver_id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.users'::regclass AND (conname='users_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.vehicle_catalog'::regclass AND (conname='vehicle_catalog_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."vehicle_catalog" ADD CONSTRAINT "vehicle_catalog_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.vehicles'::regclass AND (conname='vehicles_pkey' OR (contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)'))) THEN ALTER TABLE public."vehicles" ADD CONSTRAINT "vehicles_pkey" PRIMARY KEY (id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_extras'::regclass AND (conname='booking_extras_booking_id_extra_service_id_key' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (booking_id, extra_service_id)'))) THEN ALTER TABLE public."booking_extras" ADD CONSTRAINT "booking_extras_booking_id_extra_service_id_key" UNIQUE (booking_id, extra_service_id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.drivers'::regclass AND (conname='drivers_license_number_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (license_number)'))) THEN ALTER TABLE public."drivers" ADD CONSTRAINT "drivers_license_number_unique" UNIQUE (license_number); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.drivers'::regclass AND (conname='drivers_email_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (email)'))) THEN ALTER TABLE public."drivers" ADD CONSTRAINT "drivers_email_unique" UNIQUE (email); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.password_reset_tokens'::regclass AND (conname='password_reset_tokens_token_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (token)'))) THEN ALTER TABLE public."password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_token_unique" UNIQUE (token); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.promo_codes'::regclass AND (conname='promo_codes_code_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (code)'))) THEN ALTER TABLE public."promo_codes" ADD CONSTRAINT "promo_codes_code_unique" UNIQUE (code); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.sessions'::regclass AND (conname='sessions_token_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (token)'))) THEN ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_token_unique" UNIQUE (token); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.users'::regclass AND (conname='users_email_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (email)'))) THEN ALTER TABLE public."users" ADD CONSTRAINT "users_email_unique" UNIQUE (email); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.users'::regclass AND (conname='users_referral_code_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (referral_code)'))) THEN ALTER TABLE public."users" ADD CONSTRAINT "users_referral_code_unique" UNIQUE (referral_code); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.vehicles'::regclass AND (conname='vehicles_plate_unique' OR (contype='u' AND pg_get_constraintdef(oid)='UNIQUE (plate)'))) THEN ALTER TABLE public."vehicles" ADD CONSTRAINT "vehicles_plate_unique" UNIQUE (plate); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_sequence_nonnegative' OR (contype='c' AND pg_get_constraintdef(oid)='CHECK ((sequence >= 0))'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_sequence_nonnegative" CHECK ((sequence >= 0)); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_departure_after_arrival' OR (contype='c' AND pg_get_constraintdef(oid)='CHECK (((departed_at IS NULL) OR (arrived_at IS NOT NULL)))'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_departure_after_arrival" CHECK (((departed_at IS NULL) OR (arrived_at IS NOT NULL))); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_kind_check' OR (contype='c' AND pg_get_constraintdef(oid)='CHECK ((kind = ANY (ARRAY[''stop''::text, ''final''::text])))'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_kind_check" CHECK ((kind = ANY (ARRAY['stop'::text, 'final'::text]))); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_driver_blocks'::regclass AND (conname='booking_driver_blocks_booking_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."booking_driver_blocks" ADD CONSTRAINT "booking_driver_blocks_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_driver_blocks'::regclass AND (conname='booking_driver_blocks_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."booking_driver_blocks" ADD CONSTRAINT "booking_driver_blocks_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_extras'::regclass AND (conname='booking_extras_extra_service_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (extra_service_id) REFERENCES extra_services(id)'))) THEN ALTER TABLE public."booking_extras" ADD CONSTRAINT "booking_extras_extra_service_id_fkey" FOREIGN KEY (extra_service_id) REFERENCES extra_services(id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_extras'::regclass AND (conname='booking_extras_booking_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."booking_extras" ADD CONSTRAINT "booking_extras_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_departed_by_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (departed_by_driver_id) REFERENCES drivers(id) ON DELETE SET NULL'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_departed_by_driver_id_fkey" FOREIGN KEY (departed_by_driver_id) REFERENCES drivers(id) ON DELETE SET NULL; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_arrived_by_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (arrived_by_driver_id) REFERENCES drivers(id) ON DELETE SET NULL'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_arrived_by_driver_id_fkey" FOREIGN KEY (arrived_by_driver_id) REFERENCES drivers(id) ON DELETE SET NULL; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.booking_itinerary_stops'::regclass AND (conname='booking_itinerary_stops_booking_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."booking_itinerary_stops" ADD CONSTRAINT "booking_itinerary_stops_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.bookings'::regclass AND (conname='bookings_selected_vehicle_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (selected_vehicle_id) REFERENCES driver_vehicles(id)'))) THEN ALTER TABLE public."bookings" ADD CONSTRAINT "bookings_selected_vehicle_id_fkey" FOREIGN KEY (selected_vehicle_id) REFERENCES driver_vehicles(id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.compliance_documents'::regclass AND (conname='compliance_documents_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id)'))) THEN ALTER TABLE public."compliance_documents" ADD CONSTRAINT "compliance_documents_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id); END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_locations'::regclass AND (conname='driver_locations_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."driver_locations" ADD CONSTRAINT "driver_locations_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_locations'::regclass AND (conname='driver_locations_booking_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL'))) THEN ALTER TABLE public."driver_locations" ADD CONSTRAINT "driver_locations_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_service_zones'::regclass AND (conname='driver_service_zones_zone_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (zone_id) REFERENCES geo_zones(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."driver_service_zones" ADD CONSTRAINT "driver_service_zones_zone_id_fkey" FOREIGN KEY (zone_id) REFERENCES geo_zones(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_service_zones'::regclass AND (conname='driver_service_zones_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."driver_service_zones" ADD CONSTRAINT "driver_service_zones_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_vehicles'::regclass AND (conname='driver_vehicles_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."driver_vehicles" ADD CONSTRAINT "driver_vehicles_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_warnings'::regclass AND (conname='driver_warnings_booking_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL'))) THEN ALTER TABLE public."driver_warnings" ADD CONSTRAINT "driver_warnings_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.driver_warnings'::regclass AND (conname='driver_warnings_driver_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."driver_warnings" ADD CONSTRAINT "driver_warnings_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE; END IF; END $baseline$;
DO $baseline$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.object_owners'::regclass AND (conname='object_owners_owner_user_id_fkey' OR (contype='f' AND pg_get_constraintdef(oid)='FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE'))) THEN ALTER TABLE public."object_owners" ADD CONSTRAINT "object_owners_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE; END IF; END $baseline$;
