-- Additive migration. Apply to staging before production; no historical rows deleted.
-- CLI download was unavailable in this session; this timestamped migration is
-- applied and tracked through Supabase's connected migration API.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email_verified_at timestamptz;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS commission_pct numeric(6,5);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS checkout_key text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS checkout_fingerprint text;
CREATE UNIQUE INDEX IF NOT EXISTS bookings_checkout_key_unique ON public.bookings(checkout_key);
CREATE INDEX IF NOT EXISTS bookings_driver_schedule_idx ON public.bookings(driver_id, pickup_at);
CREATE INDEX IF NOT EXISTS bookings_user_pickup_idx ON public.bookings(user_id, pickup_at DESC);
CREATE INDEX IF NOT EXISTS bookings_payment_intent_idx ON public.bookings(stripe_payment_intent_id);

CREATE TABLE IF NOT EXISTS public.email_verifications (
 user_id integer PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
 token_hash text NOT NULL UNIQUE, email text NOT NULL,
 expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.mail_outbox (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dedupe_key text UNIQUE,
 recipient jsonb NOT NULL, subject text NOT NULL, html text NOT NULL, kind text NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','failed')),
 attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(),
 lease_until timestamptz, last_error text, provider_id text,
 created_at timestamptz NOT NULL DEFAULT now(), sent_at timestamptz
);
CREATE INDEX IF NOT EXISTS mail_outbox_due_idx ON public.mail_outbox(status,available_at);
CREATE TABLE IF NOT EXISTS public.payment_events (
 id text PRIMARY KEY, event_type text NOT NULL, booking_id integer,
 status text NOT NULL DEFAULT 'processing', attempts integer NOT NULL DEFAULT 1,
 last_error text, created_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.app_jobs (
 key text PRIMARY KEY, kind text NOT NULL, booking_id integer NOT NULL,
 status text NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0,
 available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz,
 last_error text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.booking_audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 booking_id integer NOT NULL, actor_user_id integer, action text NOT NULL,
 before_values jsonb, after_values jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS booking_audit_booking_idx ON public.booking_audit(booking_id,created_at);
CREATE TABLE IF NOT EXISTS public.cron_runs (
 name text PRIMARY KEY, started_at timestamptz, finished_at timestamptz,
 status text NOT NULL, last_error text
);
CREATE TABLE IF NOT EXISTS public.financial_events (
 id text PRIMARY KEY, booking_id integer, kind text NOT NULL,
 amount_cents bigint NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'usd',
 status text NOT NULL, reference text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.social_posts (
 id serial PRIMARY KEY, post_type text NOT NULL, media_kind text NOT NULL DEFAULT 'image',
 scheduled_at timestamptz NOT NULL, caption text NOT NULL DEFAULT '', hashtags text, media_url text,
 status text NOT NULL DEFAULT 'draft', ig_media_id text, published_at timestamptz, last_error text,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.social_posts ADD COLUMN IF NOT EXISTS container_id text;
ALTER TABLE public.social_posts ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 0;
ALTER TABLE public.social_posts ADD COLUMN IF NOT EXISTS lease_until timestamptz;
ALTER TABLE public.social_posts ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz NOT NULL DEFAULT now();

CREATE OR REPLACE FUNCTION public.audit_booking_change() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
 INSERT INTO public.booking_audit(booking_id,actor_user_id,action,before_values,after_values)
 VALUES (NEW.id, nullif(current_setting('app.actor_user_id',true),'')::integer, TG_OP,
 CASE WHEN TG_OP='UPDATE' THEN jsonb_build_object('status',OLD.status,'driverId',OLD.driver_id,'priceQuoted',OLD.price_quoted,'refundAmount',OLD.refund_amount) END,
 jsonb_build_object('status',NEW.status,'driverId',NEW.driver_id,'priceQuoted',NEW.price_quoted,'refundAmount',NEW.refund_amount));
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS booking_audit_changes ON public.bookings;
CREATE TRIGGER booking_audit_changes AFTER INSERT OR UPDATE OF status, driver_id, price_quoted, refund_amount
ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.audit_booking_change();
REVOKE ALL ON FUNCTION public.audit_booking_change() FROM PUBLIC, anon, authenticated;

DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['email_verifications','mail_outbox','payment_events','app_jobs','booking_audit','cron_runs','financial_events','social_posts'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated',t);
 END LOOP;
END $$;
